### ISSUE TITLE
Query parameter transformation to ease the user's work to configure a link

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/showalicense.com#17]
The site https://shields.io/ offers these automatic transformations for the query parameters as they are explained on their home page:

![captura de ecran din 2017-10-01 08-23-52](https://user-images.githubusercontent.com/198924/31052110-673e27b6-a683-11e7-8063-16332a5be4cc.png)

It would be easier for users to write custom URLs if we would do these transformations or similar ones, especially the last two for space characters. The users then will not need to URL encode spaces manually with `%20`.

Example:
```
http://showalicense.com/?fullname=Ionic%C4%83%20Biz%C4%83u%20%3Cbizauionica@gmail.com%3E%20(https%3A%2F%2Fionicabizau.net)&year=2015#license-mit
```
will become
```
http://showalicense.com/?fullname=Ionic%C4%83_Biz%C4%83u_<bizauionica@gmail.com>_(https%3A%2F%2Fionicabizau.net)&year=2015#license-mit
```

I will soon start working on this.

**Comment by IonicaBizau** [comment]
I prefer having the encoded urls because they give us more flexibility. #18 would be nice, tho! :+1:
