### ISSUE TITLE
Incorporate a customized URL editor in the website

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/showalicense.com#18]
The https://shields.io/ website has the following GUI for building an URL:

![captura de ecran din 2017-10-01 10-53-41](https://user-images.githubusercontent.com/198924/31052786-08103dc4-a697-11e7-99d6-efbaaec23ca3.png)

I would like something similar for showalicense.com based on the [Usage instructions][1] and on #17.

I will start working on a prototype.

  [1]: https://github.com/IonicaBizau/showalicense.com#usage

**Comment by IonicaBizau** [comment]
Maybe having a form with action `GET`, which being submitted will automatically encode the data in the url.

**Comment by silviubogan** [comment]
I have forked the showalicense.com repo, and at every push, GitHub tries to make my fork available at the domain in the CNAME file in the repository so it fails to build because the CNAME is already taken by your repository. In the settings page of the fork repository the option to disable GitHub Pages is disabled:

![captura de ecran din 2017-10-02 13-14-41](https://user-images.githubusercontent.com/198924/31073279-e84aaa5a-a773-11e7-8916-d0cf595b70e4.png)

The error email I get at every push to the repository is annoying. Please help me disable it.

**Comment by silviubogan** [comment]
Please tell me how to use blah to regenerate the README.md file after changing package.json's `blah` section. `blah -r` generates an almost empty README.md file missing the contents specified in `package.json`. What I added in package.json is this:

```json
{
  "h2": "Installation"
},
{
  "ul": [
    "`npm i -g browserify watchify blah`",
    "`browserify lib/index -o js/index.js`",
    "`cd build; node update-licenses-list.js; cd ..`",
    "In the end, run in parallel `npm run watch` and `npm start`",
    "Open in your browser [http://localhost:9000/index.html](http://localhost:9000/index.html)."
  ]
}
```
For now, I manually updated the README.md file.

**Comment by IonicaBizau** [comment]
> I have forked the showalicense.com repo, and at every push, GitHub tries to make my fork available at the domain in the CNAME file in the repository so it fails to build because the CNAME is already taken by your repository.

That seems like a bug. Will email GitHub about it.

**Comment by IonicaBizau** [comment]
This is what they said. Hope it helps :grin: 

> There are two different options you can take to fix this:

> If you want to keep Pages enabled then you'll need to delete the file called CNAME in the root of the repository. This will detach the custom domain from the repository, allowing builds to complete normally.

> If you don't need Pages enabled anymore then you can delete the gh-pages branch, stopping Pages from building at all.
