### ISSUE TITLE
Font Issue C & O is indistinguishable 

### ISSUE THREAD

**Issue by BrandonBoone** [IonicaBizau/showalicense.com#7]
In the bold text for "You can contribute too!" and elsewhere, the "c" characters look like "o." Zooming in corrects the issue, but at the default size they are indistinguishable. 

![image](https://cloud.githubusercontent.com/assets/5246918/12127231/0056d6b4-b3c4-11e5-91d2-81f4bb649bf0.png)

Tested in: 
- Chrome: 47.0.2526.80 m
- IE: 11.0.9600.18124

Chrome Inspector shows: 
- font-family:Chivo, serif;
- font-weight:bold;
- does not show the font-size.

**Comment by IonicaBizau** [comment]
Thanks for the heads-up, @BrandonBoone!

Does setting the `font-size` fix the problem? :thought_balloon:

**Comment by BrandonBoone** [comment]
Are you asking me to check for you if it's fixed or if setting it myself fixes the problem? :smile: 

I tried both. As I didn't see any changes after a hard refresh, I messed around a bit and `font-size:1.032em` (~`16.5px`) corrects the issue in Chrome. I didn't try IE.  

![image](https://cloud.githubusercontent.com/assets/5246918/12173218/8c15731c-b523-11e5-8f13-f21504be845b.png)

**Comment by IonicaBizau** [comment]
@BrandonBoone I currently don't have access to a computer running Windows and cannot reproduce the issue on Ubuntu.

So, if you have a fix, create a pull request and I will be thankful. :smile:

**Comment by IonicaBizau** [comment]
@BrandonBoone Addressed this in https://github.com/IonicaBizau/showalicense.com/commit/e0a59e55ecc3fde7d99eb1d8c55d8b87ec7285aa. I don't have any Windows machine around, but hopefully this got fixed. :boom:
